# Generated by Django 4.2.3 on 2023-07-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerztApp', '0003_appointmentmodel_date_appointmentmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='aerztApp.patientmodel'),
        ),
    ]
