# Generated by Django 4.2.3 on 2023-07-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerztApp', '0004_alter_appointmentmodel_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aerztApp.patientmodel'),
        ),
    ]
